baguette
acikek/chaozen pull request #14
Opened 2023-01-31 04:47 UTC by Daxz0

2023-01-31 04:54 UTC, acikek requested changes

2023-01-31 04:54 UTC, acikek commented on plugins/Denizen/scripts/baguette.dsc
> +            - inventory flag slot:hand bites:-:1
Use the `--` data action

2023-01-31 04:54 UTC, acikek commented on plugins/Denizen/scripts/baguette.dsc
> +            - narrate <[item].flag[bites]>
Debug narrate left in?

2023-01-31 04:54 UTC, acikek commented on plugins/Denizen/scripts/baguette.dsc
> +    - <&7>Its so long that it
`Its` -> `It's` (repeated on line 27)

2023-01-31 05:51 UTC, acikek requested changes

2023-01-31 05:51 UTC, acikek commented on plugins/Denizen/scripts/baguette.dsc
> +    debug: true
Stray debug

2023-01-31 05:51 UTC, acikek commented on plugins/Denizen/scripts/baguette.dsc
> +                    - define amount 8
Use a map lookup

2023-02-01 19:51 UTC, funkychicken493 requested changes

2023-02-01 19:51 UTC, funkychicken493 commented on plugins/Denizen/scripts/baguette.dsc
> +    flags:
I don't think this type of item should be stackable due to it's 'reusable' nature, if you had a stack of these and used one then the following script would appear to break. Consider adding a uniqueifier to the flags to keep these from stacking.

2023-02-01 19:57 UTC, funkychicken493 commented on plugins/Denizen/scripts/baguette.dsc
> +        allergy: true
I'm confused, what does the allergy flag do?

2023-02-01 19:57 UTC, funkychicken493 commented on plugins/Denizen/scripts/baguette.dsc
> +            - inventory adjust slot:hand "lore:<&7>Its so long that it<n><&7>takes 5 bites to eat.<n><&7><n><&7>Bites left: <&8><[item].flag[bites]>"
Small nitpick, but this repeats lore from the item information, so if you were to change your lore on the item then it wouldn't change here. I recommend pulling the lore from the item script like <script[baguette].data_key[lore]> and then removing the last line, so you may replace it with an updated amount.

2023-02-01 19:57 UTC, funkychicken493 commented on plugins/Denizen/scripts/baguette.dsc
> +            - definemap map:
Bad variable name.

2023-02-02 17:52 UTC, funkychicken493 commented on plugins/Denizen/scripts/baguette.dsc
> +            - inventory adjust slot:hand "lore:<&7>Its so long that it<n><&7>takes 5 bites to eat.<n><&7><n><&7>Bites left: <&8><[item].flag[bites]>"
```suggestion
            - inventory adjust slot:hand "lore:<[item].lore.get[1].to[-2].separated_by[<n>]><n><&7>Bites left: <&8><[item].flag[bites]>"
```

2023-02-03 04:33 UTC, creaturesofhabit requested changes

2023-02-03 04:33 UTC, creaturesofhabit commented on plugins/Denizen/scripts/baguette.dsc
> +                1: 8
this can be 10-(2x)

2023-02-03 04:33 UTC, creaturesofhabit commented on plugins/Denizen/scripts/baguette.dsc
> +            - inventory adjust slot:hand "lore:<[item].lore.get[1].to[-2].separated_by[<n>]><n><&7>Bites left: <&8><[item].flag[bites]>"
this lore change seems really hacky? It looks like you're just trying to change line 4? If so, just use <[item].lore.set[(your stuff)].at[4]>

2023-02-03 04:36 UTC, Daxz0 commented on plugins/Denizen/scripts/baguette.dsc
> +            - inventory adjust slot:hand "lore:<[item].lore.get[1].to[-2].separated_by[<n>]><n><&7>Bites left: <&8><[item].flag[bites]>"
funky did it

2023-02-03 04:38 UTC, creaturesofhabit commented on plugins/Denizen/scripts/baguette.dsc
> +            - inventory adjust slot:hand "lore:<[item].lore.get[1].to[-2].separated_by[<n>]><n><&7>Bites left: <&8><[item].flag[bites]>"
funky's solution is equally bad, but this wasn't it. In no case do you need to be rewriting the lore in it's entirety. Both of you seem to be forgetting that lore is a list and can be edited per-item

2023-02-03 05:08 UTC, Daxz0 commented
oops forgot to put the naming

2023-02-03 05:14 UTC, creaturesofhabit commented on plugins/Denizen/scripts/baguette.dsc
> +            - define amount <element[10].sub[<element[2].mul[<[item].flag[bites]>]>]>
```suggestion
            - define amount <element[10].sub[<[item].flag[bites].mul[2]>]>
```
efficiency

2023-02-03 05:20 UTC, creaturesofhabit approved these changes

2023-02-03 19:55 UTC, funkychicken493 approved these changes

2023-02-05 05:37 UTC, acikek approved these changes

2023-02-05 05:37 UTC, merged