Climbing Chalk
acikek/chaozen pull request #15
Opened 2023-01-31 06:10 UTC by cinthesize

Climbing chalk allows you to climb on iron bars, chains, fences, buttons, and the inner part of walls (not posts).

- One piece of Calcite in a crafting table nets you four pieces of climbing chalk.
- Climbing chalk lasts for five minutes, and gives you a warning when only thirty seconds remain.
- Climbing chalk status is saved on server shutdown, and player log outs, however if less than thirty seconds of time remains, it will be lost.

2023-01-31 06:20 UTC, acikek requested changes

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +    debug: false
Is this debug key needed?

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +    - <&7>Strengthens your grip.
Make this a different color, as it's sort of like the item "motto" instead of the actual description

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +    - <&7>Sneak + Right Click in air to apply.
Can you use a keybind text format for this?

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +climbing_chalk_handler:
(All throughout this script) use config color codes

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +climbing_chalk_handler:
(All throughout this script) small nitpick, but maybe use a flag map of `climbing_chalk` and then have keys like `.active` etc

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +        - foreach <server.online_players_flagged[climbing_chalk_active]> as:plyr:
Use the `__player` def

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +            - flag <[plyr]> climbing_chalk_active:!
Extract the core logic of these into a task

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +        - adjust <player> send_climbable_materials:<server.vanilla_tagged_materials[climbable].include[iron_bars|chain].include[<server.vanilla_tagged_materials[walls]>].include[<server.vanilla_tagge
Extract this into a task as well

2023-01-31 06:20 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +    - if !<[plyr].is_online> || <[plyr].flag_expiration[climbing_chalk_active].duration_since[<util.time_now>].is_more_than[30s]>:
We've been using word operators like `not`, `or`, etc.
You don't have to change it, though

2023-01-31 20:21 UTC, cinthesize commented
Changes made, lmk if theres anything else i missed, or if i did anything wrong <3

2023-01-31 20:24 UTC, acikek requested changes

2023-01-31 20:24 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> -    debug: false
Stray debug

2023-01-31 20:24 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +
I meant use the color codes in the denizen config, like `<&[base]>` and `<&[emphasis]>`

2023-01-31 20:24 UTC, acikek commented on plugins/Denizen/scripts/climbing_chalk.dsc
> +            - run climbing_chalk_save_duration def:<player>
You don't need to pass the `<player>` in. This becomes the linked player, so you can even use `<player>` inside that task.

2023-01-31 20:46 UTC, cinthesize commented
Hiiiii i tried again

2023-02-01 03:53 UTC, acikek approved these changes

2023-02-01 03:55 UTC, merged